### ISSUE TITLE
Add sort function to table 

### ISSUE THREAD

**Issue by tak-bro** [oh-my-github/registry#37]

**Comment by 1ambda** [comment]
@tocology Could you create pull request and mention @njir and me? 

Thanks :)

**Comment by tocology** [comment]
@1ambda It will be developed simply by `sort` method of array. And that is related to #43 issue; When the TableHeaderColumns are clicked, the rows should be sorted. 

So, please check this issue from @njir.

@njir Please fix the bugs and then provide messages to @1ambda  and me when you create pull request.

Thanks :)

**Comment by tak-bro** [comment]
@tocology Copy that

**Comment by tak-bro** [comment]
The bug is about "update date" #45.
