### ISSUE TITLE
Enable table header to be clicked

### ISSUE THREAD

**Issue by tocology** [oh-my-github/registry#43]
We need a way for table headers to deal with 'onClick' event, however, the 'TableHeaderColumn' of Material UI doesn't have the functionality.

**Comment by tocology** [comment]
@njir Please create TableHeaderTypes.

**Comment by tak-bro** [comment]
@tocology Roger that

**Comment by tak-bro** [comment]
Bug exists. Have to fix it. not close

**Comment by tak-bro** [comment]
onClick func isn't supported after v0.15 on material-ui
we have no method using onClick
